package ru.tanexc.tree.presentation.theme.Colors

import androidx.compose.ui.graphics.Color

data class DefaultColorScheme(

    override val md_theme_light_primary: Color = Color(0xFF006B56),
    override val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_primaryContainer: Color = Color(0xFF7DF8D5),
    override val md_theme_light_onPrimaryContainer: Color = Color(0xFF002018),
    override val md_theme_light_secondary: Color = Color(0xFF4B635B),
    override val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_secondaryContainer: Color = Color(0xFFCDE9DE),
    override val md_theme_light_onSecondaryContainer: Color = Color(0xFF072019),
    override val md_theme_light_tertiary: Color = Color(0xFF416276),
    override val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_tertiaryContainer: Color = Color(0xFFC4E7FF),
    override val md_theme_light_onTertiaryContainer: Color = Color(0xFF001E2D),
    override val md_theme_light_error: Color = Color(0xFFBA1A1A),
    override val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_light_onError: Color = Color(0xFFFFFFFF),
    override val md_theme_light_onErrorContainer: Color = Color(0xFF410002),
    override val md_theme_light_background: Color = Color(0xFFFBFDFA),
    override val md_theme_light_onBackground: Color = Color(0xFF191C1B),
    override val md_theme_light_surface: Color = Color(0xFFFBFDFA),
    override val md_theme_light_onSurface: Color = Color(0xFF191C1B),
    override val md_theme_light_surfaceVariant: Color = Color(0xFFDBE5DF),
    override val md_theme_light_onSurfaceVariant: Color = Color(0xFF3F4945),
    override val md_theme_light_outline: Color = Color(0xFF6F7975),
    override val md_theme_light_inverseOnSurface: Color = Color(0xFFEFF1EE),
    override val md_theme_light_inverseSurface: Color = Color(0xFF2E312F),
    override val md_theme_light_inversePrimary: Color = Color(0xFF5FDBBA),
    override val md_theme_light_shadow: Color = Color(0xFF000000),
    override val md_theme_light_surfaceTint: Color = Color(0xFF006B56),
    override val md_theme_light_outlineVariant: Color = Color(0xFFBFC9C4),
    override val md_theme_light_scrim: Color = Color(0xFF000000),

    override val md_theme_dark_primary: Color = Color(0xFF5FDBBA),
    override val md_theme_dark_onPrimary: Color = Color(0xFF00382C),
    override val md_theme_dark_primaryContainer: Color = Color(0xFF005141),
    override val md_theme_dark_onPrimaryContainer: Color = Color(0xFF7DF8D5),
    override val md_theme_dark_secondary: Color = Color(0xFFB2CCC2),
    override val md_theme_dark_onSecondary: Color = Color(0xFF1D352E),
    override val md_theme_dark_secondaryContainer: Color = Color(0xFF344C44),
    override val md_theme_dark_onSecondaryContainer: Color = Color(0xFFCDE9DE),
    override val md_theme_dark_tertiary: Color = Color(0xFFA9CBE2),
    override val md_theme_dark_onTertiary: Color = Color(0xFF0E3446),
    override val md_theme_dark_tertiaryContainer: Color = Color(0xFF284B5E),
    override val md_theme_dark_onTertiaryContainer: Color = Color(0xFFC4E7FF),
    override val md_theme_dark_error: Color = Color(0xFFFFB4AB),
    override val md_theme_dark_errorContainer: Color = Color(0xFF93000A),
    override val md_theme_dark_onError: Color = Color(0xFF690005),
    override val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_dark_background: Color = Color(0xFF191C1B),
    override val md_theme_dark_onBackground: Color = Color(0xFFE1E3E0),
    override val md_theme_dark_surface: Color = Color(0xFF191C1B),
    override val md_theme_dark_onSurface: Color = Color(0xFFE1E3E0),
    override val md_theme_dark_surfaceVariant: Color = Color(0xFF3F4945),
    override val md_theme_dark_onSurfaceVariant: Color = Color(0xFFBFC9C4),
    override val md_theme_dark_outline: Color = Color(0xFF89938E),
    override val md_theme_dark_inverseOnSurface: Color = Color(0xFF191C1B),
    override val md_theme_dark_inverseSurface: Color = Color(0xFFE1E3E0),
    override val md_theme_dark_inversePrimary: Color = Color(0xFF006B56),
    override val md_theme_dark_shadow: Color = Color(0xFF000000),
    override val md_theme_dark_surfaceTint: Color = Color(0xFF5FDBBA),
    override val md_theme_dark_outlineVariant: Color = Color(0xFF3F4945),
    override val md_theme_dark_scrim: Color = Color(0xFF000000),


    override val seed: Color = Color(0xFF8FD7C0)
) : AppColorScheme
